language: node_js
node_js: 18.16.0
git:
  depth: false
dist: focal
env:
  - BUILD_DATE=`date "+%Y-%m-%d"` COMMIT_HASH=`git rev-parse --short=11 HEAD`
notifications:
  slack:
    rooms:
      - ibm-systems-z:GsrFzDjDjUXPTi8zgEH5VMfU#linux-io-liz-devops
    on_success: change
    on_failure: always
before_script:
  - travis_retry npm install -g license-checker-rseidelsohn
  - travis_retry npm install
  - perl -i -p -e 's/BUILD_DATE/$ENV{BUILD_DATE}/' src/components/About/About.jsx
  - perl -i -p -e 's/COMMIT_HASH/$ENV{COMMIT_HASH}/' src/components/About/About.jsx
  - perl -i -p -e 's/URL_PATH_TOKEN/$ENV{URL_PATH_TOKEN}/' .env.github
  - perl -pi -e 's/vite build/vite build --mode github --base=\/$ENV{URL_PATH_TOKEN}\/liz\//' package.json
script:
  - npm run build
after_success:
  - git clone https://${GHE_TOKEN}@github.ibm.com/${URL_PATH_TOKEN}/liz.wiki.git
  - echo "# Overview" > liz.wiki/Open-Source-Development-Dependencies.md
  - echo "" >> liz.wiki/Open-Source-Development-Dependencies.md
  - echo "~~~" >> liz.wiki/Open-Source-Development-Dependencies.md
  - license-checker-rseidelsohn --development --excludePackages liz --summary >> liz.wiki/Open-Source-Development-Dependencies.md
  - echo "~~~" >> liz.wiki/Open-Source-Development-Dependencies.md
  - echo "# Dependency List" >> liz.wiki/Open-Source-Development-Dependencies.md
  - echo "" >> liz.wiki/Open-Source-Development-Dependencies.md
  - echo "Open Source dependencies that will be used to build the UI." >> liz.wiki/Open-Source-Development-Dependencies.md
  - echo "" >> liz.wiki/Open-Source-Development-Dependencies.md
  - license-checker-rseidelsohn --development --markdown --excludePackages liz >> liz.wiki/Open-Source-Development-Dependencies.md
  - echo "# Overview" > liz.wiki/Open-Source-Production-Dependencies.md
  - echo "" >> liz.wiki/Open-Source-Production-Dependencies.md
  - echo "~~~" >> liz.wiki/Open-Source-Production-Dependencies.md
  - license-checker-rseidelsohn --production --excludePackages liz --summary >> liz.wiki/Open-Source-Production-Dependencies.md
  - echo "~~~" >> liz.wiki/Open-Source-Production-Dependencies.md
  - echo "# Dependency List" >> liz.wiki/Open-Source-Production-Dependencies.md
  - echo "" >> liz.wiki/Open-Source-Production-Dependencies.md
  - echo "Open Source dependencies that will be consumed by the UI during runtime after its deployment." >> liz.wiki/Open-Source-Production-Dependencies.md
  - echo "" >> liz.wiki/Open-Source-Production-Dependencies.md
  - license-checker-rseidelsohn --production --markdown --excludePackages liz >> liz.wiki/Open-Source-Production-Dependencies.md
  - cd liz.wiki
  - git remote add origin-wiki https://${GHE_TOKEN}@github.ibm.com/${URL_PATH_TOKEN}/liz.wiki.git > /dev/null 2>&1
  - git add Open-Source-Development-Dependencies.md Open-Source-Production-Dependencies.md
  - git commit -m "update dependencies"
  - git pull --rebase
  - git push --quiet --set-upstream origin-wiki master
deploy:
  provider: pages
  local_dir: dist
  github_url: github.ibm.com
  skip_cleanup: true
  github_token: $GHE_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: main
    condition: $DEPLOY_PAGES = true
