language: node_js
node_js: 18.12.1
git:
  depth: false
dist: focal
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHE_TOKEN
  keep_history: true
  on:
    branch: main
