language: node_js
node_js: 18.12.1
git:
  depth: false
dist: focal
script:
  - npm run build
deploy:
  provider: pages
  github_url: github.ibm.com
  skip_cleanup: true
  github_token: $GHE_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: main
