language: node_js
node_js: 20.11.1
git:
    depth: false
dist: focal
env:
    - BUILD_DATE=`date "+%Y-%m-%d"` COMMIT_HASH_SHORT=`git rev-parse --short=11 HEAD` COMMIT_HASH_LONG=`git rev-parse HEAD`
notifications:
    slack:
        rooms:
            - ibm-systems-z:GsrFzDjDjUXPTi8zgEH5VMfU#linux-io-liz-devops
        on_success: change
        on_failure: always
before_script:
    - travis_retry npm install -g license-checker-rseidelsohn
    - travis_retry npm install
    - perl -i -p -e 's/BUG_TRACKER/$ENV{BUG_TRACKER}/' public/config/app/config.json
    - perl -i -p -e 's/KNOWN_ISSUES/$ENV{KNOWN_ISSUES}/' public/config/app/config.json
    - perl -i -p -e 's/BUILD_DATE/$ENV{BUILD_DATE}/' public/config/app/config.json
    - perl -i -p -e 's/COMMIT_HASH_SHORT/$ENV{COMMIT_HASH_SHORT}/' public/config/app/config.json
    - perl -i -p -e 's/COMMIT_HASH_LONG/$ENV{COMMIT_HASH_LONG}/' public/config/app/config.json
    - perl -i -p -e 's/SHOW_NOTICE/$ENV{SHOW_NOTICE}/' public/config/app/config.json
    - perl -i -p -e 's/URL_PATH_TOKEN/$ENV{URL_PATH_TOKEN}/' .env.github
    - perl -pi -e 's/vite build/vite build --mode github --base=\/$ENV{URL_PATH_TOKEN}\/liz\//' package.json
script:
    - npm run build
