= Installation assistant for Linux on IBM Z
Author: Daniel S. Haischt <daniel.haischt@de.ibm.com>
:toc: macro
:source-highlighter: pygments

++++
<p align="center">
  <a href="https://travis.ibm.com/linuxonz/liz">
    <img alt="Travis" src="https://v3.travis.ibm.com/linuxonz/liz.svg?token=sTwrf5YsyjBkhBTKWnZE&branch=main">
  </a>
</p>
++++



_Installation assistant for Linux on IBM Z that is supposed to be run on GitHub Pages._

toc::[]

== Known issues

A list of known issues is maintained at https://github.ibm.com/linuxonz/liz/wiki/Known-Issues[this location]. You may review it prior to reporting an issue.

== Prerequisites

* Node Version Manager (0.39.2 or latest)
* NodeJS (20.11.1 or latest)
* NPM (10.5.0 or latest)

== Overview

The Installation assistant for Linux on IBM Z (Stage 1) is supposed to be build and deployed to a GitHub Pages instance. There it will be served as a web application. It is supposed to streamline the workflow of creating a so called parameter file that would ease and thus automate the installation process.

The application implements a parameter file generation feature for which there's no competitor. Linux distributions as mentioned provide both installer technology based on traditional GUI toolkits (GTK/KDE) and those that are web based and thus run in the browser.

For the latter these type of installer lack the specific s390 feature set we thus intend to provide to significantly ease the installation journey for Linux on IBM Z and thus drive customers towards IBM Z due to the simplification approach the contribution provides.

The line-item feature allows to provide a self-service approach by having the application deployed and hosted on a standard HTTP server without the need to install it locally something of which we anticipate that it will reduce involving IBM support for instances where the customer could be using the line-item feature isntead to accomplish the task of installing Linux on a s390 system.

== Governance

This repository contains the following files. They are provide to govern the contribution and development process accordingly.

* link:CONTRIBUTING.adoc[CONTRIBUTING]: Contribution guidelines
* link:LICENSE[LICENSE]: The MIT license that applies to this package
* link:CHANGELOG[CHANGELOG]: The history of liz versions
* link:AUTHORS[AUTHORS]: A list of all authors of the liz package
* link:CODINGSTYLE.adoc[CODINGSTYLE]: Recommendations for writing liz code

== Repository layout

The repository is structured the following way.

1. `public` - localized strings and config files that are used by the app.
2. `src` - source files. Mainly JavaScript or JSX code.

=== Source folder layout

1. `components` - contains UI components as used by the app.
2. `content` - contains page content such as the landing and edit page.
3. `contexts` - contains contexts that gets instantiated via `createContext` and used by the various components.
4. `reducers` - contains reducers that manage the state for the various components.
5. `routes` - contains code to establish and manage the routes for the various pages.
6. `states` - contains the states for the various components.
7. `uiUtil`, `util` - utility functions.

== Testing

=== Unit Testing

Automated testing is currently unavailable. It is planned to provide test automation for unit tests based on https://jestjs.io/[Jest] and https://vitest.dev/[Vitest], 

=== Functional Verification

Functional verification testing (FVT) currently is a manual test. There are https://github.ibm.com/linuxonz/liz/wiki/Functional-Verification-Testing[test buckets] available that can be used to manually regression test the application workflow.

=== Accessibility Testing

Accessibility testing needs to be done manually. The https://www.ibm.com/able/toolkit/[IBM Equal Access Toolkit] provides a browser plug-in to analyze each page according to particular accessibility rules it is using. There are https://github.ibm.com/linuxonz/liz/wiki/Accessibility-Verification-Testing[instructions] available how to install and use this plug-in.
