import React from "react";
import PropTypes from "prop-types";
import { ProgressIndicator, ProgressStep } from "@carbon/react";
import "./_installer-flow.scss";

const InstallerFlow = ({ onProgress, progressStep, progressStepCompletion, progressStepInvalidation }) => {
  return (
    <>
      <div className="installer-flow__heading">Getting Started</div>
      <ProgressIndicator
        vertical
        currentIndex={progressStep}
        onChange={(index) => onProgress(index)}
      >
        <ProgressStep
          invalid={progressStepInvalidation.inputFileSelection}
          complete={false}
          current={progressStep === 0}
          label="Choose your input file"
          secondaryLabel="This virtual machijne currently doesn't have a Host OS. Let's begin by adding your ISO file."
        />
        <ProgressStep
          invalid={progressStepInvalidation.information}
          complete={false}
          current={progressStep === 1}
          label="Display information"
          secondaryLabel="Taken from the ISO file you have uploaded."
        />
        <ProgressStep
          invalid={progressStepInvalidation.hint}
          complete={false}
          current={progressStep === 2}
          label="Display hint"
          secondaryLabel="Infos needed to complete subsequent steps,"
        />
        <ProgressStep
          invalid={progressStepInvalidation.networkDevice}
          complete={false}
          current={progressStep === 3}
          label="Network device"
          secondaryLabel="If you are comming from DPM, the information will be autogenerated from there."
        />
        <ProgressStep
          invalid={progressStepInvalidation.networkAddress}
          complete={false}
          current={progressStep === 4}
          label="Network address"
          secondaryLabel="Once the installation is complete, you're set to start managing."
        />
        <ProgressStep
          invalid={progressStepInvalidation.installationParameters}
          complete={false}
          current={progressStep === 5}
          label="Installation parameters"
          secondaryLabel="Optional."
        />
        <ProgressStep
          invalid={progressStepInvalidation.miscParameters}
          complete={false}
          current={progressStep === 6}
          label="Miscellaneous parameters"
          secondaryLabel="Optional."
        />
        <ProgressStep
          invalid={progressStepInvalidation.downloadParamFile}
          complete={false}
          current={progressStep === 7}
          label="Download param file"
          secondaryLabel=""
        />
        <ProgressStep
          invalid={progressStepInvalidation.nextStep}
          complete={false}
          current={progressStep === 8}
          label="Next Steps"
          secondaryLabel=""
        />
      </ProgressIndicator>
    </>
  );
};

InstallerFlow.propTypes = {
  onProgress: PropTypes.func.isRequired,
  progressStep: PropTypes.number.isRequired,
  progressStepCompletion: PropTypes.shape({
    inputFileSelection: PropTypes.bool.isRequired,
    information: PropTypes.bool.isRequired,
    hint: PropTypes.bool.isRequired,
    networkDevice: PropTypes.bool.isRequired,
    networkAddress: PropTypes.bool.isRequired,
    installationParameters: PropTypes.bool.isRequired,
    miscParameters: PropTypes.bool.isRequired,
    downloadParamFile: PropTypes.bool.isRequired,
    nextStep: PropTypes.bool.isRequired
  }).isRequired,
  progressStepInvalidation: PropTypes.shape({
    inputFileSelection: PropTypes.bool.isRequired,
    information: PropTypes.bool.isRequired,
    hint: PropTypes.bool.isRequired,
    networkDevice: PropTypes.bool.isRequired,
    networkAddress: PropTypes.bool.isRequired,
    installationParameters: PropTypes.bool.isRequired,
    miscParameters: PropTypes.bool.isRequired,
    downloadParamFile: PropTypes.bool.isRequired,
    nextStep: PropTypes.bool.isRequired
  }).isRequired
};

export default InstallerFlow;
