import React, { useState } from "react";
import { ProgressIndicator, ProgressStep, Grid, Column } from "@carbon/react";
import {
  Information,
  InputFileSelection,
  InstallationParameters,
  MiscParameters,
  NetworkAddress,
  NetworkDevice,
} from "../../components/panels";
import "./_landing-page.scss";

const renderPanel = (step) => {
  let markup;

  switch (step) {
    case 0:
      markup = InputFileSelection();
      break;
    case 1:
      markup = Information();
      break;
    case 2:
      markup = NetworkDevice();
      break;
    case 3:
      markup = NetworkAddress();
      break;
    case 4:
      markup = InstallationParameters();
      break;
    case 5:
      markup = MiscParameters();
      break;
    default:
      markup = <div>Panel not yet implemented.</div>;
  }

  return markup;
};

const LandingPage = () => {
  const [step, setStep] = useState(0);
  const panelMarkup = renderPanel(step);

  return (
    <>
      <Grid className="landing-page__grid">
        <Column sm={2} md={3} lg={4} className="landing-page__installer-steps">
          <div className="landing-page__heading">Getting Started</div>
          <ProgressIndicator
            vertical
            currentIndex={step}
            onChange={(index) => setStep(index)}
          >
            <ProgressStep
              complete={false}
              current={step === 0}
              label="Choose your input file"
              secondaryLabel="This virtual machijne currently doesn't have a Host OS. Let's begin by adding your ISO file."
            />
            <ProgressStep
              complete={false}
              current={step === 1}
              label="Display information"
              secondaryLabel="Taken from the ISO file you have uploaded."
            />
            <ProgressStep
              complete={false}
              current={step === 2}
              label="Network device"
              secondaryLabel="If you are comming from DPM, the information will be autogenerated from there."
            />
            <ProgressStep
              complete={false}
              current={step === 3}
              label="Network address"
              secondaryLabel="Once the installation is complete, you're set to start managing."
            />
            <ProgressStep
              complete={false}
              current={step === 4}
              label="Installation parameters"
              secondaryLabel="Optional."
            />
            <ProgressStep
              complete={false}
              current={step === 5}
              label="Miscellaneous parameters"
              secondaryLabel="Optional."
            />
          </ProgressIndicator>
        </Column>
        <Column
          sm={6}
          md={8}
          lg={12}
          className="landing-page__grey-column-background"
        >
          {panelMarkup}
        </Column>
      </Grid>
    </>
  );
};

export default LandingPage;
